### ISSUE TITLE
Loading screen feed

### ISSUE THREAD

**Issue by danana** [okapistudio/deepstash#1]
We need a loading screen for the first time you open the app feed -- it takes a few seconds for us to bring all the info in (and it always depends on the user's connection) and we need to display something.
https://trello.com/c/iaEG89Pc/31-load-screen

**Comment by danana** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Load screen](https://trello.com/c/iaEG89Pc/31-load-screen)

**Comment by mateioprea** [comment]
Done
