### ISSUE TITLE
Animatie scroll in Topic/Author feed

### ISSUE THREAD

**Issue by danana** [okapistudio/deepstash#14]
De implementat animatia corecta
https://trello.com/c/xiDT6AIh/38-animation-topic-feed

**Comment by danana** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Animation topic feed](https://trello.com/c/xiDT6AIh/38-animation-topic-feed)

**Comment by mateioprea** [comment]
FIXED <3
