### ISSUE TITLE
Simple sharing of insights

### ISSUE THREAD

**Issue by danana** [okapistudio/deepstash#4]
Share: insight link - asta putem deja implementa.
https://trello.com/c/luyGg2Vc/6-simple-sharing-of-insights

**Comment by danana** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Simple sharing of insights](https://trello.com/c/luyGg2Vc/6-simple-sharing-of-insights)

**Comment by mateioprea** [comment]
@danana ce share-uim de fapt? nu inteleg

**Comment by mateioprea** [comment]
This is kind of done. Asteptam dupa ei un titlu si un mesaj pentru share
